version: '3'

services:
  app:
    build: python/.
    env_file: .env
    ports:
      - '5000:5000'
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - rabbitmq
  rabbitmq:
    ports:
      - '5672:5672'
    build: rabbitmq/.
